# 错误处理

几乎所有语言都有自己的错误处理机制 node提供了domain模块用于处理异步代码的错误.NodeJs官方强烈建议当捕获到异常后立即重启程序而不是让其继续执行 发生异常后的程序处于不确定的运行状态 如果不立即退出程序可能会发生严重内存泄漏

## domain

在了解domain之前需要理解域的该你那.一个域就是一个js运行环境 如果一个异常没被捕获 将作为一个全局异常被抛出.NodeJs通过process对象提供了捕获全局异常的方法.

      // process捕获
      process.on('uncaughtException', function (err) {
        console.log('Error: %s', err.message);
      });
      
      setTimeout(function (fn) {
        fn();
      });
      // Error: undefined is not a function


      // domain方式捕获异常
      function async(request, callback) {
        // Do something.
        asyncA(request, function (data) {
          // Do something
          asyncB(request, function(data){
            asyncC(request, function (data) {
              // Do something
              callback(data);
            });
          });
        });
      }

      http.createServer(function (request, response) {
        var d = domain.create();
        d.on('error', function () {
          response.writeHead(500);
          response.end();
        });
        d.run(function () {
          async(request, function (data) {
            response.writeHead(200);
            response.end(data);
          });
        });
      })